pipeline {
    
    agent any

    environment {
        PULUMI_STACK_BUCKET = "doneuxservices-pulumi-state?region=eu-west-2"

        // can use "pulumi stack -Q" to find this
        PULUMI_STACK = "organization/rng-infra/dev"
    }

    stages {
            stage ("Setup") {
                steps {
                    sh "npm i"
                }
                post {
                    success {
                        echo "Setup success"
                    }
                    failure {
                        echo "Setup failure"
                    }
                }
                
            }

            stage ("Build") {
                steps {
                    sh "npm run build"
                }
                post {
                    success {
                        echo "Build success"
                    }
                    failure {
                        echo "Build failure"
                    }
                }
            }

            stage ("Quality Gate: Static Analysis") {
                steps {
                    sh "npm run prettier:ci"
                    sh "npm run lint:ci"
                }
                post {
                    success {
                        echo "Static Analysis Success"
                    }
                    failure {
                        echo "Static Analysis Failure"
                    }
                }
            }

            stage ("Quality Gate: Composition Analysis") {
                steps {
                    sh "npm run test"
                }
                post {
                    success {
                        echo "Quality composition analysis success"
                    }
                    failure {
                        echo "Quality composition analysis failure"
                    }
                }
            }

            stage ("Deploy") {

                when {
                    anyOf {
                        branch 'master';
                    }
                }

                steps {
                    sh "curl -fsSL https://get.pulumi.com | sh"
                    sh "$HOME/.pulumi/bin/pulumi version"

                    withCredentials([aws(credentialsId: "AWS_CREDENTIALS")]){
                        withEnv(["PATH+PULUMI=$HOME/.pulumi/bin"]) {
                            sh "pulumi login 's3://${PULUMI_STACK_BUCKET}'"
                            dir("infra") {
                                sh "npm i"
                                sh "pulumi stack select ${PULUMI_STACK}"
                                withCredentials([string(credentialsId: 'PULUMI_CONFIG_PASSPHRASE', variable: "PULUMI_CONFIG_PASSPHRASE")]) {
                                    sh "pulumi up --yes"
                                }
                            }  
                        }

                    }
                }
                post {
                    success {
                        echo "Deploy success"
                    }
                    failure {
                        echo "Deploy failure"
                    }
                }
            }
        
    }

}